### ISSUE TITLE
autocompletion not working on macOS

### ISSUE THREAD

**Issue by mlcsthor** [voronkovich/gitignore.plugin.zsh#7] opened 2020-03-10 14:35 UTC
Hello,
I don't know if my problem comes from the plugin or from my configuration, but the autocompletion lists my files instead of the available templates.

<img width="261" alt="Capture d’écran 2020-03-10 à 15 34 31" src="https://user-images.githubusercontent.com/22675769/76323235-bd869200-62e4-11ea-9b02-8d1b2bf8a504.png">

**Comment by voronkovich** [comment] 2020-03-10 15:11
@mlcsthor, try to fix autocompletion by executing this commands on your terminal:
```zsh
$ compaudit | xargs -I % chmod g-w "%";
$ compaudit | xargs -I % chown $USER "%";
$ rm ~/.zcompdump*;
$ compinit;
```
BTW, Sometimes ZSH autocompletion suddenly stops to work, so I have this function on my [.zshrc](https://github.com/voronkovich/dotfiles/blob/19a1ac5894198aeb199495715ace03cdaa94226f/.zshrc#L132)
```zsh
fix-autocompletion() {
    compaudit | xargs -I % chmod g-w "%";
    compaudit | xargs -I % chown $USER "%";
    rm ~/.zcompdump*;
    compinit;
}
```

**Comment by mlcsthor** [comment] 2020-03-10 23:18
I've tried but unfortunately it doesn't work :/
I even tried to redo a complete installation of zsh, oh-my-zsh, antigen and the plugin under macOS and Windows with WSL, I get the same result.

**Comment by voronkovich** [comment] 2020-03-11 11:53
@mlcsthor, I think the problem is caused by Antigen (See: https://github.com/zsh-users/antigen/issues/698 and https://github.com/zsh-users/antigen/issues/701).

Try to install the plugin manually:

```zsh
$ cd /tmp
$ git clone --recursive https://github.com/voronkovich/gitignore.plugin.zsh
$ source gitignore.plugin.zsh/gitignore.plugin.zsh
$ gi <TAB> # Should work fine
```

**Comment by mlcsthor** [comment] 2020-03-16 23:55
It works on Windows but not on macOS, strangely enough. It's like it freezes while searching for completions.

**Comment by voronkovich** [comment] 2020-03-17 11:26
@mlcsthor, Sorry, I have no MacOS (I use Linux), so I can't help you with this issue. Try to find the solution here: https://github.com/ohmyzsh/ohmyzsh/issues/5651 and here: https://stackoverflow.com/a/26479426 

I'm closing this issue because it's not related to the plugin.

**Closed as completed by voronkovich** 2020-03-17 11:26 UTC
Labels: bug

**Comment by ajanian** [comment] 2020-04-19 16:52
I figured out why.  This will work if you try to prepend everything with an "L" so Lvis [TAB] will work I believe.  The solution is in issue #8 and it has to do with the sed expression.
